server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/fallback/userfallback
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/department/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallbackuri: forward:/fallback/departmentfallback
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:2000

management:
  endpoint:
    hystrix:
      stream:
        enabled: true
logging:
  file:
    name: "C:/Users/kashish3/Downloads/Microservice/logs.log"

