spring:
  application:
    name: USER-SERVICE
  zipkin:
    base-url: http://localhost:9411
    #Database Details for the h2 Database
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/spring-boot-h2-user-db;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

#Server Port Details
server:
  port: 0
logging:
  file:
    name: "C:/Users/kashish3/Downloads/Microservice/logs.log"
